<a href="https://colab.research.google.com/github/Fei-Q/dsst389/blob/main/nb/notebook04a.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Notebook04a

### Setup

Run all of the following before starting the notebook.

In [1]:
! wget -q -nc https://raw.githubusercontent.com/taylor-arnold/fds-py/refs/heads/main/funs.py

In [2]:

import numpy as np
import polars as pl

from funs import *
from plotnine import *
from polars import col as c
theme_set(theme_minimal())

ub = "https://raw.githubusercontent.com/taylor-arnold/fds-py-nb/refs/heads/main/"

In [3]:
movie = pl.read_csv(ub + "data/movies_50_years.csv")
color = pl.read_csv(ub + "data/movies_50_years_color.csv")
genre = pl.read_csv(ub + "data/movies_50_years_genre.csv")
people = pl.read_csv(ub + "data/movies_50_years_people.csv")

### Questions

In this notebook, we will learn how to combine information from multiple datasets using joins. The movie data has been split into several tables: `movie` contains basic information about each film (runtime, rating, etc.), `genre` lists the genres associated with each film, `color` contains information about the colors in each movie's poster, and `people` has information about the cast and crew. Because some movie titles are duplicated across different years, we will always join by both year and title to ensure we match records correctly.

Create a new column in the `movie` dataset that computes the ratio of the number of ratings to the runtime. This gives a rough sense of audience engagement per minute of film.

In [8]:
movie.head(n=2)

shape: (2, 12)
┌──────┬────────────┬─────┬─────────┬───┬──────────────┬──────────────┬──────────────┬─────────────┐
│ year ┆ title      ┆ mpa ┆ runtime ┆ … ┆ poster_brigh ┆ poster_satur ┆ poster_edgen ┆ description │
│ ---  ┆ ---        ┆ --- ┆ ---     ┆   ┆ tness        ┆ ation        ┆ ess          ┆ ---         │
│ i64  ┆ str        ┆ str ┆ i64     ┆   ┆ ---          ┆ ---          ┆ ---          ┆ str         │
│      ┆            ┆     ┆         ┆   ┆ f64          ┆ f64          ┆ f64          ┆             │
╞══════╪════════════╪═════╪═════════╪═══╪══════════════╪══════════════╪══════════════╪═════════════╡
│ 1970 ┆ Love Story ┆ PG  ┆ 100     ┆ … ┆ 79.039734    ┆ 8.029792     ┆ 4.586166     ┆ A boy and a │
│      ┆            ┆     ┆         ┆   ┆              ┆              ┆              ┆ girl from   │
│      ┆            ┆     ┆         ┆   ┆              ┆              ┆              ┆ differen…   │
│ 1970 ┆ Airport    ┆ G   ┆ 137     ┆ … ┆ 70.73516     ┆ 29.284572    ┆ 4.954735     ┆ A bomber on │
│      ┆            ┆     ┆         ┆   ┆              ┆              ┆              ┆ board an    │
│      ┆            ┆     ┆         ┆   ┆              ┆              ┆              ┆ airplane,…  │
└──────┴────────────┴─────┴─────────┴───┴──────────────┴──────────────┴──────────────┴─────────────┘

In [7]:
(
    movie
    .with_columns(
        rating_runtime_ratio = c.rating_count / c.runtime
    )
)
movie.head(n=2)

shape: (2, 12)
┌──────┬────────────┬─────┬─────────┬───┬──────────────┬──────────────┬──────────────┬─────────────┐
│ year ┆ title      ┆ mpa ┆ runtime ┆ … ┆ poster_brigh ┆ poster_satur ┆ poster_edgen ┆ description │
│ ---  ┆ ---        ┆ --- ┆ ---     ┆   ┆ tness        ┆ ation        ┆ ess          ┆ ---         │
│ i64  ┆ str        ┆ str ┆ i64     ┆   ┆ ---          ┆ ---          ┆ ---          ┆ str         │
│      ┆            ┆     ┆         ┆   ┆ f64          ┆ f64          ┆ f64          ┆             │
╞══════╪════════════╪═════╪═════════╪═══╪══════════════╪══════════════╪══════════════╪═════════════╡
│ 1970 ┆ Love Story ┆ PG  ┆ 100     ┆ … ┆ 79.039734    ┆ 8.029792     ┆ 4.586166     ┆ A boy and a │
│      ┆            ┆     ┆         ┆   ┆              ┆              ┆              ┆ girl from   │
│      ┆            ┆     ┆         ┆   ┆              ┆              ┆              ┆ differen…   │
│ 1970 ┆ Airport    ┆ G   ┆ 137     ┆ … ┆ 70.73516     ┆ 29.284572    ┆ 4.954735     ┆ A bomber on │
│      ┆            ┆     ┆         ┆   ┆              ┆              ┆              ┆ board an    │
│      ┆            ┆     ┆         ┆   ┆              ┆              ┆              ┆ airplane,…  │
└──────┴────────────┴─────┴─────────┴───┴──────────────┴──────────────┴──────────────┴─────────────┘

Using the `movie` dataset, create a scatter plot with runtime on the x-axis and the IMDB rating on the y-axis.

Create a boxplot showing the distribution of poster brightness for each MPA rating category.

Now let's start working with multiple tables. Join the `genre` table to the `movie` table. Remember to join on both year and title since some titles appear in multiple years.

Using the joined data, compute the average poster brightness and average poster saturation for each genre. Then create a scatter plot of these averages with genre labels next to each point.

The `people` table contains information about cast and crew, including a predicted gender and a confidence score for that prediction. Filter the people data to only starring roles where the gender confidence is greater than 0.8. Then join this to the genre table. For each genre, compute the proportion of these roles that are female and the total count. Sort by the proportion of female roles and display all results.

Let's find the most common dominant poster color for each genre. Start with the `color` table and filter to just the hue colors. For each movie, find the color with the highest percentage (this is the dominant hue). Keep only movies where the dominant hue makes up more than 5% of the poster. Join this to the genre table, then count how often each color appears as the dominant hue within each genre. Finally, find the single most common dominant color for each genre.

Now, let's see an example of how to use an semi-join. First, create a table called `movie_long` that consists of all films that have a run time greater than 2.5 hours (150 minutes).

Then, draw a plot showing the number films that have a long runtime by their genre using a semi-join. Try to make the plot look nice. Note: Yes, you could do this in other ways in this simple case. Semi- and anti-joins are very useful as our analyses become more complex.

We've mentioned that some titles are repeated in the data and therefore we always need to group by title and year. Find all of the titles that are repeated. Print all of the rows of the result and order by the counts.