<a href="https://colab.research.google.com/github/Fei-Q/dsst389/blob/main/nb/notebook02c.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Notebook02c

### Setup

Run all of the following before starting the notebook.

In [1]:
! wget -q -nc https://raw.githubusercontent.com/taylor-arnold/fds-py/refs/heads/main/funs.py

In [2]:
import numpy as np
import polars as pl

from funs import *
from plotnine import *
from polars import col as c
theme_set(theme_minimal())

ub = "https://raw.githubusercontent.com/taylor-arnold/fds-py-nb/refs/heads/main/"

In [3]:
film = pl.read_csv(ub + "data/criterion.csv").filter(~c.rating_imdb.is_null())

### Questions

In this notebook, we will practice data manipulation using a dataset of films from the Criterion Collection. The `film` dataset contains information about each movie including its title, director, year of release, runtime, and IMDB rating.

In [5]:
film.head(n=2)

shape: (2, 18)
┌───────────┬────────────┬──────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ imdb_id   ┆ title      ┆ year ┆ language   ┆ … ┆ wikipedia_ ┆ wikipedia_ ┆ budget_ra ┆ box_offic │
│ ---       ┆ ---        ┆ ---  ┆ ---        ┆   ┆ descriptio ┆ extract    ┆ w         ┆ e_raw     │
│ str       ┆ str        ┆ i64  ┆ str        ┆   ┆ n          ┆ ---        ┆ ---       ┆ ---       │
│           ┆            ┆      ┆            ┆   ┆ ---        ┆ str        ┆ i64       ┆ i64       │
│           ┆            ┆      ┆            ┆   ┆ str        ┆            ┆           ┆           │
╞═══════════╪════════════╪══════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ tt0012349 ┆ The Kid    ┆ 1921 ┆ None|Engli ┆ … ┆ 1921       ┆ The Kid is ┆ 250000    ┆ null      │
│           ┆            ┆      ┆ sh         ┆   ┆ silent     ┆ a 1921     ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ film by    ┆ American   ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ Charlie    ┆ sil…       ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ Ch…        ┆            ┆           ┆           │
│ tt0012364 ┆ The        ┆ 1921 ┆ None|Swedi ┆ … ┆ 1921 film  ┆ The        ┆ null      ┆ null      │
│           ┆ Phantom    ┆      ┆ sh         ┆   ┆ by Victor  ┆ Phantom    ┆           ┆           │
│           ┆ Carriage   ┆      ┆            ┆   ┆ Sjöström   ┆ Carriage   ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆            ┆ is a 1921… ┆           ┆           │
└───────────┴────────────┴──────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

Start by sorting the films by their IMDB rating, with the lowest-rated films at the top.

In [7]:
(
    film.sort("rating_imdb")
)

shape: (1_470, 18)
┌───────────┬────────────┬──────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ imdb_id   ┆ title      ┆ year ┆ language   ┆ … ┆ wikipedia_ ┆ wikipedia_ ┆ budget_ra ┆ box_offic │
│ ---       ┆ ---        ┆ ---  ┆ ---        ┆   ┆ descriptio ┆ extract    ┆ w         ┆ e_raw     │
│ str       ┆ str        ┆ i64  ┆ str        ┆   ┆ n          ┆ ---        ┆ ---       ┆ ---       │
│           ┆            ┆      ┆            ┆   ┆ ---        ┆ str        ┆ i64       ┆ i64       │
│           ┆            ┆      ┆            ┆   ┆ str        ┆            ┆           ┆           │
╞═══════════╪════════════╪══════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ tt0062492 ┆ Wild 90    ┆ 1968 ┆ English    ┆ … ┆ 1968 film  ┆ Wild 90 is ┆ null      ┆ null      │
│           ┆            ┆      ┆            ┆   ┆ by Norman  ┆ a 1968 exp ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ Mailer     ┆ erimental… ┆           ┆           │
│ tt0064373 ┆ All        ┆ 1969 ┆ Japanese   ┆ … ┆ 1969 film  ┆ All        ┆ null      ┆ null      │
│           ┆ Monsters   ┆      ┆            ┆   ┆ by Ishirō  ┆ Monsters   ┆           ┆           │
│           ┆ Attack     ┆      ┆            ┆   ┆ Honda      ┆ Attack  is ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆            ┆ a 1969…    ┆           ┆           │
│ tt0063195 ┆ Genocide   ┆ 1968 ┆ Japanese   ┆ … ┆ 1968       ┆ Genocide   ┆ null      ┆ null      │
│           ┆            ┆      ┆            ┆   ┆ Japanese   ┆ is a 1968  ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ film       ┆ Japanese   ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆            ┆ s…         ┆           ┆           │
│ tt0064625 ┆ Maidstone  ┆ 1970 ┆ English    ┆ … ┆ 1970 film  ┆ Maidstone  ┆ null      ┆ null      │
│           ┆            ┆      ┆            ┆   ┆ by Norman  ┆ is a 1970  ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ Mailer     ┆ American   ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆            ┆ i…         ┆           ┆           │
│ tt2006181 ┆ Jellyfish  ┆ 2013 ┆ Japanese   ┆ … ┆ 2013       ┆ Jellyfish  ┆ null      ┆ null      │
│           ┆ Eyes       ┆      ┆            ┆   ┆ Japanese   ┆ Eyes  is a ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ film       ┆ 2013 Japa… ┆           ┆           │
│ …         ┆ …          ┆ …    ┆ …          ┆ … ┆ …          ┆ …          ┆ …         ┆ …         │
│ tt0048434 ┆ Night and  ┆ 1956 ┆ French     ┆ … ┆ 1956       ┆ Night and  ┆ null      ┆ null      │
│           ┆ Fog        ┆      ┆            ┆   ┆ French     ┆ Fog is a   ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ film       ┆ 1956       ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆            ┆ French…    ┆           ┆           │
│ tt0056058 ┆ Harakiri   ┆ 1962 ┆ Japanese   ┆ … ┆ Japanese   ┆ Harakiri   ┆ null      ┆ 15000     │
│           ┆            ┆      ┆            ┆   ┆ jidaigeki  ┆ is a 1962  ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ film       ┆ Japanese   ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆            ┆ j…         ┆           ┆           │
│ tt0102926 ┆ The        ┆ 1991 ┆ English|La ┆ … ┆ 1991       ┆ The        ┆ 19000000  ┆ 130742922 │
│           ┆ Silence of ┆      ┆ tin        ┆   ┆ horror     ┆ Silence of ┆           ┆           │
│           ┆ the Lambs  ┆      ┆            ┆   ┆ film by    ┆ the Lambs  ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ Jonathan   ┆ is a …     ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ D…         ┆            ┆           ┆           │
│ tt0090015 ┆ Shoah      ┆ 1985 ┆ German|Heb ┆ … ┆ 1985       ┆ Shoah is a ┆ null      ┆ null      │
│           ┆            ┆      ┆ rew|Polish ┆   ┆ French doc ┆ 1985       ┆           ┆           │
│           ┆            ┆      ┆ |Yiddish|F ┆   ┆ umentary   ┆ French     ┆           ┆           │
│           ┆            ┆      ┆ …          ┆   ┆ film b…    ┆ documen…   ┆           ┆           │
│ tt0050083 ┆ 12 Angry   ┆ 1957 ┆ English    ┆ … ┆ American   ┆ 12 Angry   ┆ 340000    ┆ null      │
│           ┆ Men        ┆      ┆            ┆   ┆ legal      ┆ Men is a   ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ drama film ┆ 1957       ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ by S…      ┆ America…   ┆           ┆           │
└───────────┴────────────┴──────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

Now, sort the films by runtime with the longest films at the top.

In [8]:
(
    film.sort("runtime_raw", descending=True)
)

shape: (1_470, 18)
┌───────────┬────────────┬──────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ imdb_id   ┆ title      ┆ year ┆ language   ┆ … ┆ wikipedia_ ┆ wikipedia_ ┆ budget_ra ┆ box_offic │
│ ---       ┆ ---        ┆ ---  ┆ ---        ┆   ┆ descriptio ┆ extract    ┆ w         ┆ e_raw     │
│ str       ┆ str        ┆ i64  ┆ str        ┆   ┆ n          ┆ ---        ┆ ---       ┆ ---       │
│           ┆            ┆      ┆            ┆   ┆ ---        ┆ str        ┆ i64       ┆ i64       │
│           ┆            ┆      ┆            ┆   ┆ str        ┆            ┆           ┆           │
╞═══════════╪════════════╪══════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ tt0023261 ┆ No Blood   ┆ 1932 ┆ None|Japan ┆ … ┆ 1932       ┆ No Blood   ┆ null      ┆ null      │
│           ┆ Relation   ┆      ┆ ese        ┆   ┆ Japanese   ┆ Relation   ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ film       ┆ is a 1932  ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆            ┆ J…         ┆           ┆           │
│ tt0024214 ┆ Apart from ┆ 1933 ┆ None|Japan ┆ … ┆ 1933       ┆ Apart From ┆ null      ┆ null      │
│           ┆ You        ┆      ┆ ese        ┆   ┆ Japanese   ┆ You  is a  ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ film       ┆ 1933 Japa… ┆           ┆           │
│ tt0025338 ┆ Street     ┆ 1934 ┆ None       ┆ … ┆ 1934       ┆ Street     ┆ null      ┆ null      │
│           ┆ Without    ┆      ┆            ┆   ┆ Japanese   ┆ Without    ┆           ┆           │
│           ┆ End        ┆      ┆            ┆   ┆ film       ┆ End  is a  ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆            ┆ 1934 …     ┆           ┆           │
│ tt0029002 ┆ History Is ┆ 1937 ┆ English|It ┆ … ┆ 1937 film  ┆ History Is ┆ null      ┆ null      │
│           ┆ Made at    ┆      ┆ alian|Fren ┆   ┆ by Frank   ┆ Made at    ┆           ┆           │
│           ┆ Night      ┆      ┆ ch         ┆   ┆ Borzage    ┆ Night is a ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆            ┆ …          ┆           ┆           │
│ tt0031828 ┆ The Tunnel ┆ 1940 ┆ English    ┆ … ┆ 1940 film  ┆ The Proud  ┆ null      ┆ null      │
│           ┆            ┆      ┆            ┆   ┆ by Pen     ┆ Valley is  ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ Tennyson   ┆ a 1940     ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆            ┆ Eal…       ┆           ┆           │
│ …         ┆ …          ┆ …    ┆ …          ┆ … ┆ …          ┆ …          ┆ …         ┆ …         │
│ tt0056662 ┆ Vive le    ┆ 1962 ┆ French     ┆ … ┆ 1962       ┆ Vive le    ┆ null      ┆ null      │
│           ┆ tour       ┆      ┆            ┆   ┆ French     ┆ Tour is a  ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ film       ┆ 1962       ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆            ┆ French …   ┆           ┆           │
│ tt0075122 ┆ The        ┆ 1976 ┆ Persian    ┆ … ┆ 1976       ┆ The        ┆ null      ┆ null      │
│           ┆ Colours    ┆      ┆            ┆   ┆ Iranian    ┆ Colours is ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ film       ┆ a 1976     ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆            ┆ Iranian …  ┆           ┆           │
│ tt0063551 ┆ Saute ma   ┆ 1971 ┆ French     ┆ … ┆ Belgian    ┆ Chantal    ┆ null      ┆ null      │
│           ┆ ville      ┆      ┆            ┆   ┆ film       ┆ Anne       ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ director,  ┆ Akerman    ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ screenw…   ┆ was a Bel… ┆           ┆           │
│ tt0068354 ┆ La chambre ┆ 1972 ┆ French     ┆ … ┆ null       ┆ null       ┆ null      ┆ null      │
│ tt0066127 ┆ The Bread  ┆ 1970 ┆ None       ┆ … ┆ 1970 film  ┆ The Bread  ┆ null      ┆ null      │
│           ┆ and Alley  ┆      ┆            ┆   ┆            ┆ and Alley  ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆            ┆ is a 1970  ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆            ┆ …          ┆           ┆           │
└───────────┴────────────┴──────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

Select only the films that are less than 60 minutes long (i.e., short films).

In [9]:
(
    film.filter(c.runtime_raw < 60)
)

shape: (26, 18)
┌───────────┬────────────┬──────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ imdb_id   ┆ title      ┆ year ┆ language   ┆ … ┆ wikipedia_ ┆ wikipedia_ ┆ budget_ra ┆ box_offic │
│ ---       ┆ ---        ┆ ---  ┆ ---        ┆   ┆ descriptio ┆ extract    ┆ w         ┆ e_raw     │
│ str       ┆ str        ┆ i64  ┆ str        ┆   ┆ n          ┆ ---        ┆ ---       ┆ ---       │
│           ┆            ┆      ┆            ┆   ┆ ---        ┆ str        ┆ i64       ┆ i64       │
│           ┆            ┆      ┆            ┆   ┆ str        ┆            ┆           ┆           │
╞═══════════╪════════════╪══════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ tt0021576 ┆ À Propos   ┆ 1930 ┆ None       ┆ … ┆ 1930 film  ┆ À propos   ┆ null      ┆ null      │
│           ┆ de Nice    ┆      ┆            ┆   ┆            ┆ de Nice is ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆            ┆ a 1930     ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆            ┆ sil…       ┆           ┆           │
│ tt0022036 ┆ Flunky,    ┆ 1931 ┆ None|Japan ┆ … ┆ 1931       ┆ Flunky,    ┆ null      ┆ null      │
│           ┆ Work Hard! ┆      ┆ ese        ┆   ┆ Japanese   ┆ Work Hard! ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ film       ┆ is a 1931  ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆            ┆ …          ┆           ┆           │
│ tt0024803 ┆ Zero for   ┆ 1933 ┆ French     ┆ … ┆ 1933       ┆ Zero for   ┆ null      ┆ null      │
│           ┆ Conduct    ┆      ┆            ┆   ┆ French     ┆ Conduct is ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ film       ┆ a 1933     ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆            ┆ Fre…       ┆           ┆           │
│ tt0028445 ┆ A Day in   ┆ 1936 ┆ French     ┆ … ┆ 1946       ┆ Partie de  ┆ null      ┆ null      │
│           ┆ the        ┆      ┆            ┆   ┆ French     ┆ campagne   ┆           ┆           │
│           ┆ Country    ┆      ┆            ┆   ┆ film       ┆ is a       ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆            ┆ French…    ┆           ┆           │
│ tt0038182 ┆ The Men    ┆ 1945 ┆ Japanese   ┆ … ┆ 1945       ┆ The Men    ┆ null      ┆ null      │
│           ┆ Who Tread  ┆      ┆            ┆   ┆ Japanese   ┆ Who Tread  ┆           ┆           │
│           ┆ on the     ┆      ┆            ┆   ┆ film by    ┆ on the     ┆           ┆           │
│           ┆ Tiger…     ┆      ┆            ┆   ┆ Akira Ku…  ┆ Tiger…     ┆           ┆           │
│ …         ┆ …          ┆ …    ┆ …          ┆ … ┆ …          ┆ …          ┆ …         ┆ …         │
│ tt0079704 ┆ Paul       ┆ 1979 ┆ English|Ma ┆ … ┆ 1979 film  ┆ Paul       ┆ null      ┆ null      │
│           ┆ Robeson:   ┆      ┆ ndarin     ┆   ┆            ┆ Robeson:   ┆           ┆           │
│           ┆ Tribute to ┆      ┆            ┆   ┆            ┆ Tribute to ┆           ┆           │
│           ┆ an Ar…     ┆      ┆            ┆   ┆            ┆ an Ar…     ┆           ┆           │
│ tt0081204 ┆ Mur murs   ┆ 1981 ┆ French|Eng ┆ … ┆ 1980 docum ┆ Mur Murs   ┆ null      ┆ null      │
│           ┆            ┆      ┆ lish|Itali ┆   ┆ entary     ┆ is a 1981  ┆           ┆           │
│           ┆            ┆      ┆ an|Spanish ┆   ┆ film by    ┆ documentar ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ Agnès…     ┆ y…         ┆           ┆           │
│ tt0083727 ┆ Chambre    ┆ 1982 ┆ English|Fr ┆ … ┆ 1982       ┆ Room 666   ┆ null      ┆ null      │
│           ┆ 666        ┆      ┆ ench|Germa ┆   ┆ French     ┆ is a 1982  ┆           ┆           │
│           ┆            ┆      ┆ n|Italian| ┆   ┆ film       ┆ documentar ┆           ┆           │
│           ┆            ┆      ┆ …          ┆   ┆            ┆ y…         ┆           ┆           │
│ tt0085641 ┆ Fellow     ┆ 1983 ┆ Persian    ┆ … ┆ 1983       ┆ Fellow     ┆ null      ┆ null      │
│           ┆ Citizen    ┆      ┆            ┆   ┆ Iranian    ┆ Citizen is ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ film       ┆ a 1983     ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆            ┆ Irani…     ┆           ┆           │
│ tt0111460 ┆ Total      ┆ 1994 ┆ Finnish|En ┆ … ┆ 1994       ┆ Total      ┆ null      ┆ null      │
│           ┆ Balalaika  ┆      ┆ glish|Fren ┆   ┆ Finnish    ┆ Balalaika  ┆           ┆           │
│           ┆ Show       ┆      ┆ ch|Russian ┆   ┆ film       ┆ Show is a  ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆            ┆ 1994…      ┆           ┆           │
└───────────┴────────────┴──────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

Select all films directed by Charles Chaplin.

In [10]:
(
    film.filter(c.director == "Charles Chaplin")
)

shape: (8, 18)
┌───────────┬────────────┬──────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ imdb_id   ┆ title      ┆ year ┆ language   ┆ … ┆ wikipedia_ ┆ wikipedia_ ┆ budget_ra ┆ box_offic │
│ ---       ┆ ---        ┆ ---  ┆ ---        ┆   ┆ descriptio ┆ extract    ┆ w         ┆ e_raw     │
│ str       ┆ str        ┆ i64  ┆ str        ┆   ┆ n          ┆ ---        ┆ ---       ┆ ---       │
│           ┆            ┆      ┆            ┆   ┆ ---        ┆ str        ┆ i64       ┆ i64       │
│           ┆            ┆      ┆            ┆   ┆ str        ┆            ┆           ┆           │
╞═══════════╪════════════╪══════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ tt0012349 ┆ The Kid    ┆ 1921 ┆ None|Engli ┆ … ┆ 1921       ┆ The Kid is ┆ 250000    ┆ null      │
│           ┆            ┆      ┆ sh         ┆   ┆ silent     ┆ a 1921     ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ film by    ┆ American   ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ Charlie    ┆ sil…       ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ Ch…        ┆            ┆           ┆           │
│ tt0014624 ┆ A Woman of ┆ 1923 ┆ English    ┆ … ┆ 1923 drama ┆ A Woman of ┆ 351000    ┆ 634000    │
│           ┆ Paris: A   ┆      ┆            ┆   ┆ film by    ┆ Paris is a ┆           ┆           │
│           ┆ Drama of   ┆      ┆            ┆   ┆ Charlie    ┆ 1923 sil…  ┆           ┆           │
│           ┆ F…         ┆      ┆            ┆   ┆ Cha…       ┆            ┆           ┆           │
│ tt0018773 ┆ The Circus ┆ 1928 ┆ None|Engli ┆ … ┆ 1928 film  ┆ The Circus ┆ null      ┆ null      │
│           ┆            ┆      ┆ sh         ┆   ┆ by Charlie ┆ is a 1928  ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ Chaplin    ┆ silent ro… ┆           ┆           │
│ tt0021749 ┆ City       ┆ 1931 ┆ None|Engli ┆ … ┆ 1931       ┆ City       ┆ 1500000   ┆ 5000000   │
│           ┆ Lights     ┆      ┆ sh         ┆   ┆ American   ┆ Lights is  ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ silent     ┆ a 1931     ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ film       ┆ American…  ┆           ┆           │
│ tt0027977 ┆ Modern     ┆ 1936 ┆ English    ┆ … ┆ 1936       ┆ Modern     ┆ 1500000   ┆ 1400000   │
│           ┆ Times      ┆      ┆            ┆   ┆ comedy     ┆ Times is a ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ film by    ┆ 1936       ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ Charlie    ┆ America…   ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ Ch…        ┆            ┆           ┆           │
│ tt0032553 ┆ The Great  ┆ 1940 ┆ English|Es ┆ … ┆ 1940       ┆ The Great  ┆ 2000000   ┆ 5000000   │
│           ┆ Dictator   ┆      ┆ peranto|La ┆   ┆ American   ┆ Dictator   ┆           ┆           │
│           ┆            ┆      ┆ tin        ┆   ┆ film by    ┆ is a 1940  ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ Charlie …  ┆ A…         ┆           ┆           │
│ tt0039631 ┆ Monsieur   ┆ 1947 ┆ English|Fr ┆ … ┆ 1947 film  ┆ Monsieur   ┆ 2000000   ┆ null      │
│           ┆ Verdoux    ┆      ┆ ench|Latin ┆   ┆ by Charlie ┆ Verdoux is ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ Chaplin    ┆ a 1947     ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆            ┆ Ame…       ┆           ┆           │
│ tt0044837 ┆ Limelight  ┆ 1952 ┆ English    ┆ … ┆ 1952 film  ┆ Limelight  ┆ 900000    ┆ 1000000   │
│           ┆            ┆      ┆            ┆   ┆ by Charlie ┆ is a 1952  ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ Chaplin    ┆ American   ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆            ┆ c…         ┆           ┆           │
└───────────┴────────────┴──────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

Select all films directed by either Charles Chaplin or Jean-Luc Godard.

In [11]:
(
    film.filter(c.director.is_in(["Charles Chaplin", "Jean-Luc Godard"]))
)

shape: (19, 18)
┌───────────┬────────────┬──────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ imdb_id   ┆ title      ┆ year ┆ language   ┆ … ┆ wikipedia_ ┆ wikipedia_ ┆ budget_ra ┆ box_offic │
│ ---       ┆ ---        ┆ ---  ┆ ---        ┆   ┆ descriptio ┆ extract    ┆ w         ┆ e_raw     │
│ str       ┆ str        ┆ i64  ┆ str        ┆   ┆ n          ┆ ---        ┆ ---       ┆ ---       │
│           ┆            ┆      ┆            ┆   ┆ ---        ┆ str        ┆ i64       ┆ i64       │
│           ┆            ┆      ┆            ┆   ┆ str        ┆            ┆           ┆           │
╞═══════════╪════════════╪══════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ tt0012349 ┆ The Kid    ┆ 1921 ┆ None|Engli ┆ … ┆ 1921       ┆ The Kid is ┆ 250000    ┆ null      │
│           ┆            ┆      ┆ sh         ┆   ┆ silent     ┆ a 1921     ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ film by    ┆ American   ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ Charlie    ┆ sil…       ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ Ch…        ┆            ┆           ┆           │
│ tt0014624 ┆ A Woman of ┆ 1923 ┆ English    ┆ … ┆ 1923 drama ┆ A Woman of ┆ 351000    ┆ 634000    │
│           ┆ Paris: A   ┆      ┆            ┆   ┆ film by    ┆ Paris is a ┆           ┆           │
│           ┆ Drama of   ┆      ┆            ┆   ┆ Charlie    ┆ 1923 sil…  ┆           ┆           │
│           ┆ F…         ┆      ┆            ┆   ┆ Cha…       ┆            ┆           ┆           │
│ tt0018773 ┆ The Circus ┆ 1928 ┆ None|Engli ┆ … ┆ 1928 film  ┆ The Circus ┆ null      ┆ null      │
│           ┆            ┆      ┆ sh         ┆   ┆ by Charlie ┆ is a 1928  ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ Chaplin    ┆ silent ro… ┆           ┆           │
│ tt0021749 ┆ City       ┆ 1931 ┆ None|Engli ┆ … ┆ 1931       ┆ City       ┆ 1500000   ┆ 5000000   │
│           ┆ Lights     ┆      ┆ sh         ┆   ┆ American   ┆ Lights is  ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ silent     ┆ a 1931     ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ film       ┆ American…  ┆           ┆           │
│ tt0027977 ┆ Modern     ┆ 1936 ┆ English    ┆ … ┆ 1936       ┆ Modern     ┆ 1500000   ┆ 1400000   │
│           ┆ Times      ┆      ┆            ┆   ┆ comedy     ┆ Times is a ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ film by    ┆ 1936       ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ Charlie    ┆ America…   ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ Ch…        ┆            ┆           ┆           │
│ …         ┆ …          ┆ …    ┆ …          ┆ … ┆ …          ┆ …          ┆ …         ┆ …         │
│ tt0060675 ┆ Masculine  ┆ 1966 ┆ French|Swe ┆ … ┆ 1966 film  ┆ Masculin   ┆ null      ┆ null      │
│           ┆ Feminine   ┆      ┆ dish|Engli ┆   ┆ by         ┆ féminin:   ┆           ┆           │
│           ┆            ┆      ┆ sh         ┆   ┆ Jean-Luc   ┆ 15         ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ Godard     ┆ Specific … ┆           ┆           │
│ tt0060304 ┆ 2 or 3     ┆ 1967 ┆ French|Ita ┆ … ┆ 1967 film  ┆ Two or     ┆ null      ┆ null      │
│           ┆ Things I   ┆      ┆ lian|Engli ┆   ┆ by         ┆ Three      ┆           ┆           │
│           ┆ Know About ┆      ┆ sh         ┆   ┆ Jean-Luc   ┆ Things I   ┆           ┆           │
│           ┆ Her        ┆      ┆            ┆   ┆ Godard     ┆ Know Abo…  ┆           ┆           │
│ tt0062480 ┆ Weekend    ┆ 1967 ┆ French     ┆ … ┆ Film by    ┆ Weekend is ┆ null      ┆ null      │
│           ┆            ┆      ┆            ┆   ┆ Jean-Luc   ┆ a 1967     ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ Godard     ┆ postmodern ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆            ┆ b…         ┆           ┆           │
│ tt0079854 ┆ Every Man  ┆ 1980 ┆ French|Ita ┆ … ┆ 1980       ┆ Every Man  ┆ null      ┆ null      │
│           ┆ for        ┆      ┆ lian       ┆   ┆ French     ┆ for        ┆           ┆           │
│           ┆ Himself    ┆      ┆            ┆   ┆ film       ┆ Himself is ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆            ┆ a 198…     ┆           ┆           │
│ tt0093349 ┆ King Lear  ┆ 1987 ┆ French|Eng ┆ … ┆ 1987 film  ┆ King Lear  ┆ null      ┆ null      │
│           ┆            ┆      ┆ lish|Russi ┆   ┆ directed   ┆ is a 1987  ┆           ┆           │
│           ┆            ┆      ┆ an|Japanes ┆   ┆ by         ┆ film       ┆           ┆           │
│           ┆            ┆      ┆ …          ┆   ┆ Jean-Luc…  ┆ direc…     ┆           ┆           │
└───────────┴────────────┴──────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

Find the highest-rated film from each year. Sort the final result by year so it is easier to read.

In [15]:
(
    film
    .sort("rating_imdb", descending=True)
    .group_by("year")
    .head(n=1)
)

shape: (102, 18)
┌──────┬───────────┬────────────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ year ┆ imdb_id   ┆ title      ┆ language   ┆ … ┆ wikipedia_ ┆ wikipedia_ ┆ budget_ra ┆ box_offic │
│ ---  ┆ ---       ┆ ---        ┆ ---        ┆   ┆ descriptio ┆ extract    ┆ w         ┆ e_raw     │
│ i64  ┆ str       ┆ str        ┆ str        ┆   ┆ n          ┆ ---        ┆ ---       ┆ ---       │
│      ┆           ┆            ┆            ┆   ┆ ---        ┆ str        ┆ i64       ┆ i64       │
│      ┆           ┆            ┆            ┆   ┆ str        ┆            ┆           ┆           │
╞══════╪═══════════╪════════════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 2011 ┆ tt1440266 ┆ Pina       ┆ German|Fre ┆ … ┆ 2011 film  ┆ Pina is a  ┆ null      ┆ null      │
│      ┆           ┆            ┆ nch|Englis ┆   ┆            ┆ 2011       ┆           ┆           │
│      ┆           ┆            ┆ h|Spanish| ┆   ┆            ┆ German 3D  ┆           ┆           │
│      ┆           ┆            ┆ …          ┆   ┆            ┆ docum…     ┆           ┆           │
│ 1983 ┆ tt0084740 ┆ El Sur     ┆ Spanish    ┆ … ┆ 1983       ┆ El Sur is  ┆ null      ┆ null      │
│      ┆           ┆            ┆            ┆   ┆ Spanish    ┆ a 1983     ┆           ┆           │
│      ┆           ┆            ┆            ┆   ┆ film       ┆ Spanish    ┆           ┆           │
│      ┆           ┆            ┆            ┆   ┆            ┆ drama…     ┆           ┆           │
│ 2002 ┆ tt0310793 ┆ Bowling    ┆ English    ┆ … ┆ 2002 film  ┆ Bowling    ┆ null      ┆ null      │
│      ┆           ┆ for        ┆            ┆   ┆ by Michael ┆ for        ┆           ┆           │
│      ┆           ┆ Columbine  ┆            ┆   ┆ Moore      ┆ Columbine  ┆           ┆           │
│      ┆           ┆            ┆            ┆   ┆            ┆ is a 200…  ┆           ┆           │
│ 1969 ┆ tt0064040 ┆ Army of    ┆ French|Ger ┆ … ┆ 1969 film  ┆ Army of    ┆ null      ┆ null      │
│      ┆           ┆ Shadows    ┆ man|Englis ┆   ┆ by Jean-Pi ┆ Shadows is ┆           ┆           │
│      ┆           ┆            ┆ h          ┆   ┆ erre       ┆ a 1969     ┆           ┆           │
│      ┆           ┆            ┆            ┆   ┆ Melvi…     ┆ Fran…      ┆           ┆           │
│ 1984 ┆ tt0088196 ┆ Streetwise ┆ English    ┆ … ┆ 1984       ┆ Streetwise ┆ null      ┆ null      │
│      ┆           ┆            ┆            ┆   ┆ American   ┆ is a 1984  ┆           ┆           │
│      ┆           ┆            ┆            ┆   ┆ film       ┆ documenta… ┆           ┆           │
│ …    ┆ …         ┆ …          ┆ …          ┆ … ┆ …          ┆ …          ┆ …         ┆ …         │
│ 1979 ┆ tt0079944 ┆ Stalker    ┆ Russian    ┆ … ┆ 1979       ┆ Stalker is ┆ null      ┆ null      │
│      ┆           ┆            ┆            ┆   ┆ Soviet     ┆ a 1979     ┆           ┆           │
│      ┆           ┆            ┆            ┆   ┆ science    ┆ Soviet     ┆           ┆           │
│      ┆           ┆            ┆            ┆   ┆ fantasy    ┆ scien…     ┆           ┆           │
│      ┆           ┆            ┆            ┆   ┆ fi…        ┆            ┆           ┆           │
│ 1955 ┆ tt0048452 ┆ Ordet      ┆ Danish     ┆ … ┆ 1955       ┆ Ordet is a ┆ null      ┆ null      │
│      ┆           ┆            ┆            ┆   ┆ Danish     ┆ 1955       ┆           ┆           │
│      ┆           ┆            ┆            ┆   ┆ film       ┆ Danish     ┆           ┆           │
│      ┆           ┆            ┆            ┆   ┆            ┆ drama f…   ┆           ┆           │
│ 1944 ┆ tt0036775 ┆ Double     ┆ English    ┆ … ┆ 1944       ┆ Double     ┆ 927000    ┆ null      │
│      ┆           ┆ Indemnity  ┆            ┆   ┆ American   ┆ Indemnity  ┆           ┆           │
│      ┆           ┆            ┆            ┆   ┆ film by    ┆ is a 1944  ┆           ┆           │
│      ┆           ┆            ┆            ┆   ┆ Billy Wi…  ┆ Ame…       ┆           ┆           │
│ 1976 ┆ tt0074605 ┆ Harlan     ┆ English    ┆ … ┆ 1976       ┆ Harlan     ┆ null      ┆ null      │
│      ┆           ┆ County     ┆            ┆   ┆ American   ┆ County USA ┆           ┆           │
│      ┆           ┆ U.S.A.     ┆            ┆   ┆ documentar ┆ is a 1976  ┆           ┆           │
│      ┆           ┆            ┆            ┆   ┆ y film     ┆ Am…        ┆           ┆           │
│ 1938 ┆ tt0029947 ┆ Bringing   ┆ English    ┆ … ┆ 1938 film  ┆ Bringing   ┆ 1100000   ┆ 489000    │
│      ┆           ┆ Up Baby    ┆            ┆   ┆ by Howard  ┆ Up Baby is ┆           ┆           │
│      ┆           ┆            ┆            ┆   ┆ Hawks      ┆ a 1938     ┆           ┆           │
│      ┆           ┆            ┆            ┆   ┆            ┆ Ame…       ┆           ┆           │
└──────┴───────────┴────────────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

For each director, compute the average IMDB rating of their films and the number of films they have in the collection.

In [19]:
(
    film
    .group_by(c.director)
    .agg(
        average_rating = c.rating_imdb.mean(),
        number_of_films = pl.count()
    )
)

/tmp/ipython-input-2851715595.py:6: DeprecationWarning: `pl.count()` is deprecated. Please use `pl.len()` instead.
(Deprecated in version 0.20.5)

shape: (650, 3)
┌─────────────────────────────────┬────────────────┬─────────────────┐
│ director                        ┆ average_rating ┆ number_of_films │
│ ---                             ┆ ---            ┆ ---             │
│ str                             ┆ f64            ┆ u32             │
╞═════════════════════════════════╪════════════════╪═════════════════╡
│ Kim Ki-young                    ┆ 7.2            ┆ 1               │
│ Ishirô Honda                    ┆ 6.7            ┆ 4               │
│ Wong Kar-Wai                    ┆ 7.557143       ┆ 7               │
│ John Cameron Mitchell           ┆ 7.7            ┆ 1               │
│ Karyn Kusama                    ┆ 6.7            ┆ 1               │
│ …                               ┆ …              ┆ …               │
│ Peter Weir                      ┆ 7.15           ┆ 2               │
│ Pen Tennyson                    ┆ 6.7            ┆ 1               │
│ Apichatpong Weerasethakul       ┆ 6.7            ┆ 1               │
│ Volker Schlöndorff|Margarethe … ┆ 7.3            ┆ 1               │
│ Elio Petri                      ┆ 8.0            ┆ 1               │
└─────────────────────────────────┴────────────────┴─────────────────┘

We often want to group data by decade rather than individual years. To compute the decade from a year, we can use the expression `c.year // 10 * 10`. The `//` operator performs integer division (dividing and dropping the remainder), so for example `1987 // 10` gives `198`, and multiplying by 10 gives `1980`. Create a new column containing the decade each film was released in.

In [20]:
(
    film
    .with_columns(decade = c.year // 10 * 10)
)

shape: (1_470, 19)
┌────────────┬─────────────┬──────┬────────────┬───┬────────────┬────────────┬────────────┬────────┐
│ imdb_id    ┆ title       ┆ year ┆ language   ┆ … ┆ wikipedia_ ┆ budget_raw ┆ box_office ┆ decade │
│ ---        ┆ ---         ┆ ---  ┆ ---        ┆   ┆ extract    ┆ ---        ┆ _raw       ┆ ---    │
│ str        ┆ str         ┆ i64  ┆ str        ┆   ┆ ---        ┆ i64        ┆ ---        ┆ i64    │
│            ┆             ┆      ┆            ┆   ┆ str        ┆            ┆ i64        ┆        │
╞════════════╪═════════════╪══════╪════════════╪═══╪════════════╪════════════╪════════════╪════════╡
│ tt0012349  ┆ The Kid     ┆ 1921 ┆ None|Engli ┆ … ┆ The Kid is ┆ 250000     ┆ null       ┆ 1920   │
│            ┆             ┆      ┆ sh         ┆   ┆ a 1921     ┆            ┆            ┆        │
│            ┆             ┆      ┆            ┆   ┆ American   ┆            ┆            ┆        │
│            ┆             ┆      ┆            ┆   ┆ sil…       ┆            ┆            ┆        │
│ tt0012364  ┆ The Phantom ┆ 1921 ┆ None|Swedi ┆ … ┆ The        ┆ null       ┆ null       ┆ 1920   │
│            ┆ Carriage    ┆      ┆ sh         ┆   ┆ Phantom    ┆            ┆            ┆        │
│            ┆             ┆      ┆            ┆   ┆ Carriage   ┆            ┆            ┆        │
│            ┆             ┆      ┆            ┆   ┆ is a 1921… ┆            ┆            ┆        │
│ tt0013257  ┆ Häxan       ┆ 1922 ┆ Swedish|Da ┆ … ┆ Häxan is a ┆ 2000000    ┆ null       ┆ 1920   │
│            ┆             ┆      ┆ nish       ┆   ┆ 1922 Swedi ┆            ┆            ┆        │
│            ┆             ┆      ┆            ┆   ┆ sh-Danish… ┆            ┆            ┆        │
│ tt0014429  ┆ Safety      ┆ 1923 ┆ English    ┆ … ┆ Safety     ┆ 121000     ┆ null       ┆ 1920   │
│            ┆ Last!       ┆      ┆            ┆   ┆ Last! is a ┆            ┆            ┆        │
│            ┆             ┆      ┆            ┆   ┆ 1923       ┆            ┆            ┆        │
│            ┆             ┆      ┆            ┆   ┆ America…   ┆            ┆            ┆        │
│ tt0014624  ┆ A Woman of  ┆ 1923 ┆ English    ┆ … ┆ A Woman of ┆ 351000     ┆ 634000     ┆ 1920   │
│            ┆ Paris: A    ┆      ┆            ┆   ┆ Paris is a ┆            ┆            ┆        │
│            ┆ Drama of F… ┆      ┆            ┆   ┆ 1923 sil…  ┆            ┆            ┆        │
│ …          ┆ …           ┆ …    ┆ …          ┆ … ┆ …          ┆ …          ┆ …          ┆ …      │
│ tt27958252 ┆ Caught by   ┆ 2024 ┆ Mandarin|E ┆ … ┆ Caught by  ┆ null       ┆ null       ┆ 2020   │
│            ┆ the Tides   ┆      ┆ nglish     ┆   ┆ the Tides  ┆            ┆            ┆        │
│            ┆             ┆      ┆            ┆   ┆ is a 2024  ┆            ┆            ┆        │
│            ┆             ┆      ┆            ┆   ┆ …          ┆            ┆            ┆        │
│ tt28607951 ┆ Anora       ┆ 2024 ┆ English|Ru ┆ … ┆ Anora is a ┆ null       ┆ null       ┆ 2020   │
│            ┆             ┆      ┆ ssian|Arme ┆   ┆ 2024       ┆            ┆            ┆        │
│            ┆             ┆      ┆ nian       ┆   ┆ American   ┆            ┆            ┆        │
│            ┆             ┆      ┆            ┆   ┆ roman…     ┆            ┆            ┆        │
│ tt28618488 ┆ Vermiglio   ┆ 2024 ┆ Italian|La ┆ … ┆ Vermiglio  ┆ null       ┆ null       ┆ 2020   │
│            ┆             ┆      ┆ tin        ┆   ┆ , also     ┆            ┆            ┆        │
│            ┆             ┆      ┆            ┆   ┆ known as   ┆            ┆            ┆        │
│            ┆             ┆      ┆            ┆   ┆ The …      ┆            ┆            ┆        │
│ tt32085997 ┆ Misericordi ┆ 2024 ┆ French     ┆ … ┆ Misericord ┆ null       ┆ null       ┆ 2020   │
│            ┆ a           ┆      ┆            ┆   ┆ ia is a    ┆            ┆            ┆        │
│            ┆             ┆      ┆            ┆   ┆ 2024 black ┆            ┆            ┆        │
│            ┆             ┆      ┆            ┆   ┆ c…         ┆            ┆            ┆        │
│ tt32086077 ┆ All We      ┆ 2024 ┆ Malayalam| ┆ … ┆ All We     ┆ null       ┆ null       ┆ 2020   │
│            ┆ Imagine as  ┆      ┆ Hindi|Mara ┆   ┆ Imagine as ┆            ┆            ┆        │
│            ┆ Light       ┆      ┆ thi|Englis ┆   ┆ Light is a ┆            ┆            ┆        │
│            ┆             ┆      ┆ …          ┆   ┆ 2…         ┆            ┆            ┆        │
└────────────┴─────────────┴──────┴────────────┴───┴────────────┴────────────┴────────────┴────────┘

Now, count how many films in the collection were released in each decade.

In [23]:
(
    film
    .with_columns(decade = c.year // 10 * 10)
    .group_by(c.decade)
    .agg(n = pl.len())
)

shape: (11, 2)
┌────────┬─────┐
│ decade ┆ n   │
│ ---    ┆ --- │
│ i64    ┆ u32 │
╞════════╪═════╡
│ 1960   ┆ 303 │
│ 1950   ┆ 162 │
│ 1920   ┆ 19  │
│ 2000   ┆ 86  │
│ 1990   ┆ 154 │
│ …      ┆ …   │
│ 1930   ┆ 119 │
│ 1980   ┆ 171 │
│ 1940   ┆ 122 │
│ 2010   ┆ 55  │
│ 2020   ┆ 47  │
└────────┴─────┘

Find the directors with more than 5 films in the collection, showing their average IMDB rating. Sort the results so the highest-rated directors appear at the top.

In [26]:
(
    film
    .group_by(c.director)
    .agg(
        n_films = pl.len(),
        avg_rating = c.rating_imdb.mean()
    )
    .filter(c.n_films>5)
    .sort(c.avg_rating, descending=False)
)

shape: (48, 3)
┌─────────────────────┬─────────┬────────────┐
│ director            ┆ n_films ┆ avg_rating │
│ ---                 ┆ ---     ┆ ---        │
│ str                 ┆ u32     ┆ f64        │
╞═════════════════════╪═════════╪════════════╡
│ Chantal Akerman     ┆ 8       ┆ 6.7375     │
│ David Cronenberg    ┆ 7       ┆ 6.742857   │
│ Keisuke Kinoshita   ┆ 7       ┆ 6.842857   │
│ Nagisa Ôshima       ┆ 8       ┆ 6.85       │
│ Pier Paolo Pasolini ┆ 12      ┆ 6.941667   │
│ …                   ┆ …       ┆ …          │
│ Carl Theodor Dreyer ┆ 6       ┆ 7.683333   │
│ Richard Linklater   ┆ 6       ┆ 7.766667   │
│ Kenji Mizoguchi     ┆ 9       ┆ 7.777778   │
│ Satyajit Ray        ┆ 11      ┆ 7.981818   │
│ Charles Chaplin     ┆ 8       ┆ 8.05       │
└─────────────────────┴─────────┴────────────┘

For each director with more than 5 films in the collection, show their highest-rated film. Hint: If you sort by rating before grouping, the first title in each group will be that director's highest-rated film.

In [29]:
(
    film
    .sort("rating_imdb", descending=True)
    .group_by(c.director)
    .agg(
        n_films = pl.len(),
        title = c.title.first()
    )
    .filter(c.n_films>5)
    .drop(c.n_films)
)

shape: (48, 2)
┌─────────────────────────────────┬─────────────────────────────────┐
│ director                        ┆ title                           │
│ ---                             ┆ ---                             │
│ str                             ┆ str                             │
╞═════════════════════════════════╪═════════════════════════════════╡
│ Satyajit Ray                    ┆ The World of Apu                │
│ Michael Powell|Emeric Pressbur… ┆ The Red Shoes                   │
│ Charles Chaplin                 ┆ City Lights                     │
│ Keisuke Kinoshita               ┆ Twenty-Four Eyes                │
│ Michelangelo Antonioni          ┆ La Notte                        │
│ …                               ┆ …                               │
│ Samuel Fuller                   ┆ Pickup on South Street          │
│ Yasujirô Ozu                    ┆ Late Spring                     │
│ Pier Paolo Pasolini             ┆ Accattone                       │
│ Mikio Naruse                    ┆ When a Woman Ascends the Stair… │
│ François Truffaut               ┆ The 400 Blows                   │
└─────────────────────────────────┴─────────────────────────────────┘

By default, only the first few rows of a result are displayed. To see more rows, we can pipe the result through the `print_rows` function. Modify your previous answer to display all of the results.

In [31]:
(
    film
    .sort("rating_imdb", descending=True)
    .group_by(c.director)
    .agg(
        n_films = pl.len(),
        title = c.title.first()
    )
    .filter(c.n_films>5)
    .drop(c.n_films)
    .pipe(print_rows)
)

shape: (48, 2)
┌─────────────────────────────────┬─────────────────────────────────┐
│ director                        ┆ title                           │
│ ---                             ┆ ---                             │
│ str                             ┆ str                             │
╞═════════════════════════════════╪═════════════════════════════════╡
│ Seijun Suzuki                   ┆ Youth of the Beast              │
│ Koreyoshi Kurahara              ┆ Intimidation                    │
│ Ingmar Bergman                  ┆ Scenes from a Marriage          │
│ Rainer Werner Fassbinder        ┆ Ali: Fear Eats the Soul         │
│ Satyajit Ray                    ┆ The World of Apu                │
│ Jean Renoir                     ┆ The Rules of the Game           │
│ Ernst Lubitsch                  ┆ To Be or Not to Be              │
│ Federico Fellini                ┆ La Strada                       │
│ Louis Malle                     ┆ Au Revoir les Enfants           │
│ Jim Jarmusch                    ┆ Down by Law                     │
│ Carl Theodor Dreyer             ┆ Ordet                           │
│ David Lean                      ┆ Brief Encounter                 │
│ Agnès Varda                     ┆ The Beaches of Agnès            │
│ Richard Linklater               ┆ Before Sunrise                  │
│ Jacques Demy                    ┆ The Umbrellas of Cherbourg      │
│ Jean-Luc Godard                 ┆ Vivre sa vie                    │
│ David Lynch                     ┆ Mulholland Drive                │
│ Wes Anderson                    ┆ The Grand Budapest Hotel        │
│ Robert Bresson                  ┆ A Man Escaped                   │
│ Vittorio De Sica                ┆ Bicycle Thieves                 │
│ Wong Kar-Wai                    ┆ In the Mood for Love            │
│ Chantal Akerman                 ┆ Jeanne Dielman, 23, quai du Co… │
│ Michael Haneke                  ┆ The Seventh Continent           │
│ Terry Gilliam                   ┆ Brazil                          │
│ Wim Wenders                     ┆ Paris, Texas                    │
│ Samuel Fuller                   ┆ Pickup on South Street          │
│ Mikio Naruse                    ┆ When a Woman Ascends the Stair… │
│ David Cronenberg                ┆ A History of Violence           │
│ Masaki Kobayashi                ┆ Harakiri                        │
│ Nagisa Ôshima                   ┆ Death by Hanging                │
│ Michael Powell|Emeric Pressbur… ┆ The Red Shoes                   │
│ Julien Duvivier                 ┆ Panique                         │
│ Michelangelo Antonioni          ┆ La Notte                        │
│ Marlon Riggs                    ┆ Ethnic Notions                  │
│ Keisuke Kinoshita               ┆ Twenty-Four Eyes                │
│ Pier Paolo Pasolini             ┆ Accattone                       │
│ Charles Chaplin                 ┆ City Lights                     │
│ Yasujirô Ozu                    ┆ Late Spring                     │
│ Kenji Misumi                    ┆ Lone Wolf and Cub: Baby Cart a… │
│ Roberto Rossellini              ┆ Rome, Open City                 │
│ Kenji Mizoguchi                 ┆ Sansho the Bailiff              │
│ Akira Kurosawa                  ┆ Seven Samurai                   │
│ John Cassavetes                 ┆ A Woman Under the Influence     │
│ Abbas Kiarostami                ┆ Close-Up                        │
│ François Truffaut               ┆ The 400 Blows                   │
│ Aki Kaurismäki                  ┆ The Bohemian Life               │
│ Martin Scorsese                 ┆ The Last Waltz                  │
│ Alfred Hitchcock                ┆ Rebecca                         │
└─────────────────────────────────┴─────────────────────────────────┘